spring:
  profiles: local
  redis:
    host: 192.168.250.35
server:
  port: 8041
lotto:
  issue:
    host: "http://localhost:8051"
  draw:
    host: "http://localhost:8061"

---

spring:
  profiles: test
  redis:
    host: 10.0.0.11
server:
  port: 8041
lotto:
  issue:
    host: "http://lotto-issue"
  draw:
    host: "http://lotto-draw"
